//Console.WriteLine("Dodaj punkty zycia: ");
//string text = Console.ReadLine();
//int punktyZycia = int.Parse(text);
//Console.WriteLine("Dodaj liczbe mikstur: ");
//string text2 = Console.ReadLine();
//int liczbeMikstur = int.Parse(text2);
//Console.WriteLine("Czy masz klucz? ");
//string text3 = Console.ReadLine();
//bool klucz = bool.Parse(text3);
//Console.WriteLine("Czy masz mape?");
//string text4 = Console.ReadLine();
//bool mapa = bool.Parse(text4);
//bool zyje = punktyZycia > 0;
//bool maPelneZdrowie = punktyZycia == 100;
//bool wymagaleczenia = punktyZycia != 100;
//bool mazaopatrzeie = liczbeMikstur >= 0;
//bool maPrzedmiotNawigacyjny = klucz || mapa == true;
//bool gotowyDoWyprawy = zyje && mazaopatrzeie && maPrzedmiotNawigacyjny == true;
//Console.WriteLine($"Zyje: {zyje} \nMa pelne zdrowie: {maPelneZdrowie} \nWymaga leczenia: {wymagaleczenia} \nMa zaopatrzenie: {mazaopatrzeie} \nMa klucz lub mape: {maPrzedmiotNawigacyjny} \nGotowy do wyprawy: {gotowyDoWyprawy}");