//Console.WriteLine("Jakie masz na imie?");
//string username = Console.ReadLine();
//Console.WriteLine("Twoje maksymalne punkty zycia: ");
//string text = Console.ReadLine(); 
//int maksPunkty = int.Parse(text);
//Console.WriteLine("Twoje aktualny punkty zycia: "); 
//string text2 = Console.ReadLine();
//int aktPunkty = int.Parse(text2);
//Console.WriteLine("Twoje podstawowe obrazenie broni: ");
//string text3 = Console.ReadLine();
//int bronia = int.Parse(text3);
//Console.WriteLine("Twoje premie d//Console.WriteLine("Jakie masz na imie?");
//string username = Console.ReadLine();
//Console.WriteLine("Twoje maksymalne punkty zycia: ");
//string text = Console.ReadLine(); 
//int maksPunkty = int.Parse(text);
//Console.WriteLine("Twoje aktualny punkty zycia: "); 
//string text2 = Console.ReadLine();
//int aktPunkty = int.Parse(text2);
//Console.WriteLine("Twoje podstawowe obrazenie broni: ");
//string text3 = Console.ReadLine();
//int bronia = int.Parse(text3);
//Console.WriteLine("Twoje premie do sily: ");
//string text4 = Console.ReadLine();
//int premieDoSily = int.Parse(text4);
//Console.WriteLine("Twoj mnoznik ataku specjalnego: ");
//string text5 = Console.ReadLine();
//double mnoznik = double.Parse(text5);
//Console.WriteLine("Liczba wykonanych zwyklch atakow: ");
//string text6 = Console.ReadLine();
//int liczbaAtakow = int.Parse(text6);o sily: ");
//string text4 = Console.ReadLine();
//int premieDoSily = int.Parse(text4);
//Console.WriteLine("Twoj mnoznik ataku specjalnego: ");
//string text5 = Console.ReadLine();
//double mnoznik = double.Parse(text5);
//Console.WriteLine("Liczba wykonanych zwyklch atakow: ");
//string text6 = Console.ReadLine();
//int liczbaAtakow = int.Parse(text6);
//int zwyklyAtak = bronia + premieDoSily;
//double specjAtak = zwyklyAtak * mnoznik;
//double laczObrazenia = liczbaAtakow + specjAtak;
//bool zyje = aktPunkty > 0;
//bool maPelneZdrowie = aktPunkty == 100;
//Console.WriteLine("========== RAPORT Z WALKI ==========");
//Console.WriteLine($"Bohater: {username}");
//Console.WriteLine($"Zdrowie: {aktPunkty}/{maksPunkty} ({(double)aktPunkty:F2}%)");
//Console.WriteLine($"Zwykly atak: {zwyklyAtak}");
//Console.WriteLine($"Atak specjalny: {(int)specjAtak}");
//Console.WriteLine($"Łączne zadane obrażenia: {(int)laczObrazenia}");
//Console.WriteLine($"Zyje: {zyje} \nPelne zdrowie: {maPelneZdrowie}");
//Console.WriteLine("====================================");