Console.WriteLine("Jakie masz na imie?");
string username = Console.ReadLine();
Console.WriteLine("Jakie masz symbol na mape?");
string text4 = Console.ReadLine();
char symbol = char.Parse(text4);
Console.WriteLine("Twoje aktualny punkty zycia: "); 
string text2 = Console.ReadLine();
const int maksPunkty = 100;
int aktPunkty = int.Parse(text2);
Console.WriteLine("Twoja sila: "); 
string text7 = Console.ReadLine();
int sila = int.Parse(text7);
Console.WriteLine("Twoja premia broni: ");
string text3 = Console.ReadLine();
int premieBroni = int.Parse(text3);
Console.WriteLine("Twoj mnoznik ataku specjalnego(double): ");
string text5 = Console.ReadLine();
double mnoznik = double.Parse(text5);
Console.WriteLine("Liczba zajetnych miejsc w plecaku: ");
string text6 = Console.ReadLine();
int miejscaWPlecaku = int.Parse(text6);
const int maksPlecak = 15;
Console.WriteLine("Ile masz zlota(decimal)?");
string text8 = Console.ReadLine();
decimal zloto = decimal.Parse(text8);
Console.WriteLine("Ile czlonikow masz w swojej druzynie?"); // skrocony operator --
string text9 = Console.ReadLine();
int czloniki = int.Parse(text9);
Console.WriteLine("Czy masz mape(t/f)?");
string text10 = Console.ReadLine();
bool mapa = bool.Parse(text10);
Console.WriteLine("Czy masz jakas chorobe?");
string text11 = Console.ReadLine();
bool choroba = bool.Parse(text11);
//int zwykleObrarzenia = sila + premieBroni; lub при выводе ("..: {premiaBroni += sila}")
double atakSpecj = mnoznik * (premieBroni += sila);
decimal zlotoDoJednej = zloto / czloniki;
decimal zlotoPozostajace = zloto % czloniki;
bool zyje = aktPunkty > 0;
bool pelnieZdrowie = aktPunkty == 100;
bool leczenie = aktPunkty != 100 || choroba == true;
bool wolneMiejca = miejscaWPlecaku < maksPlecak;
bool wyprawa = wolneMiejca && zyje && leczenie && mapa == true;
Console.WriteLine("+==========================================+\n|           KARTA BOHATERA               |\n+==========================================+");
Console.WriteLine($"| Bohater: {username}\t\t\t\t{symbol} |");
Console.WriteLine("+------------------------------------------+");
Console.WriteLine($"| Zdrowie: {aktPunkty}/{maksPunkty} ({(double)aktPunkty:F2}%)                 |");
Console.WriteLine($"| Premia broni: {premieBroni}                         |\n| Zwykle obrazenia: {premieBroni += sila}                     |\n| Mnoznik ataku specjalnego: {mnoznik:F2}          | ");
Console.WriteLine($"| Obrazenia ataku specjalnego: {(int)atakSpecj}          | ");
Console.WriteLine("+------------------------------------------+");
Console.WriteLine($"| Plecak: {miejscaWPlecaku}/{maksPlecak}                            |");
Console.WriteLine($"| Wolne miejca: {maksPlecak - miejscaWPlecaku}                         |\n| Zloto: {(int)zloto}                                |\n| Liczba czlonikow druzyny: {czloniki--}             |");
Console.WriteLine($"| Zloto dla jednej osoby: {(int)zlotoDoJednej}                |\n| Zloto pozostajace w skarbu: {zlotoPozostajace}           |");
Console.WriteLine("+-----------------------------------------+");
Console.WriteLine($"| Ma mape: {mapa}                         |\n| Zyje: {zyje}                            |\n| Ma pelnie zdrowie: {pelnieZdrowie}\n| Wymaga leczenie: {leczenie}                    |");
Console.WriteLine($"| Ma miejsce w plecaku: {wolneMiejca}               |");
Console.WriteLine($"| Gotowy/a do wyptawy: {wyprawa}                |");

